DROP TABLE IF EXISTS analise_melhorias;
DROP TABLE IF EXISTS prompt_templates;
DROP TABLE IF EXISTS analises;
DROP TABLE IF EXISTS alertas;
DROP TABLE IF EXISTS ocorrencias;
DROP TABLE IF EXISTS movimentos;
DROP TABLE IF EXISTS regras;
DROP TABLE IF EXISTS produto;
DROP TABLE IF EXISTS pessoa_monitorada;

CREATE TABLE pessoa_monitorada (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf_cnpj        VARCHAR(14) NOT NULL UNIQUE,
    nome            VARCHAR(200) NOT NULL,
    tipo_pessoa     VARCHAR(2) NOT NULL CHECK (tipo_pessoa IN ('PF', 'PJ')),
    pep             BOOLEAN NOT NULL DEFAULT FALSE,
    pem             BOOLEAN NOT NULL DEFAULT FALSE,
    funcionario     BOOLEAN NOT NULL DEFAULT FALSE,
    data_cadastro   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE produto (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(30) NOT NULL UNIQUE,
    descricao   VARCHAR(200) NOT NULL
);

CREATE TABLE regras (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(30) NOT NULL UNIQUE,
    descricao   VARCHAR(200) NOT NULL,
    ativo       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE movimentos (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_monitorada_id    BIGINT NOT NULL REFERENCES pessoa_monitorada (id),
    produto_id              BIGINT NOT NULL REFERENCES produto (id),
    valor                   DECIMAL(18, 2) NOT NULL,
    data_movimento          TIMESTAMP NOT NULL,
    tipo_lancamento         VARCHAR(7) NOT NULL CHECK (tipo_lancamento IN ('CREDITO', 'DEBITO'))
);

CREATE TABLE ocorrencias (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_monitorada_id    BIGINT NOT NULL REFERENCES pessoa_monitorada (id),
    produto_id              BIGINT REFERENCES produto (id),
    status                  VARCHAR(12) NOT NULL CHECK (status IN ('ABERTA', 'EM_ANALISE', 'ENCERRADA')),
    data_abertura           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_encerramento       TIMESTAMP
);

CREATE INDEX idx_ocorrencias_pessoa_mes ON ocorrencias (pessoa_monitorada_id, data_abertura);

CREATE TABLE alertas (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_monitorada_id    BIGINT NOT NULL REFERENCES pessoa_monitorada (id),
    regra_id                BIGINT NOT NULL REFERENCES regras (id),
    data_geracao            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ocorrencia_id           BIGINT REFERENCES ocorrencias (id)
);

CREATE TABLE analises (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ocorrencia_id   BIGINT NOT NULL REFERENCES ocorrencias (id),
    analista        VARCHAR(200) NOT NULL,
    data_analise    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    parecer         CLOB NOT NULL
);

CREATE TABLE prompt_templates (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id      BIGINT NOT NULL REFERENCES produto (id),
    versao          INT NOT NULL,
    nome            VARCHAR(200) NOT NULL,
    prompt_sistema  CLOB,
    prompt_usuario  CLOB NOT NULL,
    modelo          VARCHAR(100) NOT NULL,
    temperature     DECIMAL(3, 2) NOT NULL DEFAULT 0.30,
    max_tokens      INT NOT NULL DEFAULT 600,
    ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (produto_id, versao)
);

CREATE TABLE analise_melhorias (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analise_id          BIGINT NOT NULL REFERENCES analises (id),
    prompt_template_id  BIGINT NOT NULL REFERENCES prompt_templates (id),
    texto_original      CLOB NOT NULL,
    texto_sugerido      CLOB,
    status              VARCHAR(12) NOT NULL CHECK (status IN ('GERADO', 'ACEITO', 'DESCARTADO', 'ERRO')),
    erro_mensagem       VARCHAR(500),
    solicitado_em       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    respondido_em       TIMESTAMP
);
